package com.ourwork.tntnetworkslab.ui;

import com.ourwork.tntnetworkslab.core.items.Table1;
import com.ourwork.tntnetworkslab.core.items.Table;
import com.ourwork.tntnetworkslab.core.solvers.Solver;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vasilis Naskos
 */
public class TableEditor extends javax.swing.JFrame {

    private TreeModelHandler treeModelHandler;
    private DefaultTableModel model;
    private Table table;
    
    private boolean savedOnce;
    
    /**
     * Creates new form TableEditor
     */
    public TableEditor() {
        this(new Table1());
        savedOnce = false;
    }
    
    public TableEditor(final Table table) {
        initComponents();
        
        this.table = table;
        this.savedOnce = true;
        this.setTitle(table.getTableName());
        tableNameField.setText(table.getTableName());
        
        model = createModelFromTable(table);
        jTable1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        exerciseSelector = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        saveButton = new javax.swing.JButton();
        importDataButton = new javax.swing.JButton();
        insertRowButton = new javax.swing.JButton();
        solveButton = new javax.swing.JButton();
        deleteRowButton = new javax.swing.JButton();
        tableNameField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        exerciseSelector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Άσκηση 1", "Άσκηση 2" }));
        exerciseSelector.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                exerciseSelectorItemStateChanged(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "s", "α", "B", "Q"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        saveButton.setText("Αποθήκευση");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        importDataButton.setText("Εισαγωγή");

        insertRowButton.setText("Εισαγωγή Γραμμής");
        insertRowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertRowButtonActionPerformed(evt);
            }
        });

        solveButton.setText("Υπολόγισε");
        solveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solveButtonActionPerformed(evt);
            }
        });

        deleteRowButton.setText("Διαγραφή Γραμμής");
        deleteRowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRowButtonActionPerformed(evt);
            }
        });

        tableNameField.setText("Πίνακας 1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tableNameField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(exerciseSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(importDataButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(insertRowButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteRowButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(solveButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exerciseSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(importDataButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(tableNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertRowButton)
                    .addComponent(solveButton)
                    .addComponent(deleteRowButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if (!savedOnce) {
            table = createTable();
            savedOnce = true;
            treeModelHandler.addTable(table);
        } else {
            updateTable(table);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void insertRowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertRowButtonActionPerformed
        model.insertRow(model.getRowCount(), new Object[model.getRowCount()]);
    }//GEN-LAST:event_insertRowButtonActionPerformed

    private void solveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solveButtonActionPerformed
        if (jTable1.isEditing()) {
            jTable1.getCellEditor().stopCellEditing();
        }

        updateTable(table);
        table = Solver.solve(table);
        model = createModelFromTable(table);
        jTable1.setModel(model);
    }//GEN-LAST:event_solveButtonActionPerformed

    private void deleteRowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRowButtonActionPerformed
        int[] selected = jTable1.getSelectedRows();
        
        for(int i=selected.length-1; i>=0; i--) {
            model.removeRow(selected[i]);
        }
    }//GEN-LAST:event_deleteRowButtonActionPerformed

    private void exerciseSelectorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_exerciseSelectorItemStateChanged
        table = createTable();
        model = createModelFromTable(table);
        jTable1.setModel(model);
    }//GEN-LAST:event_exerciseSelectorItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteRowButton;
    private javax.swing.JComboBox exerciseSelector;
    private javax.swing.JButton importDataButton;
    private javax.swing.JButton insertRowButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton solveButton;
    private javax.swing.JTextField tableNameField;
    // End of variables declaration//GEN-END:variables

    public void setTreeModelHandler(TreeModelHandler treeModelHandler) {
        this.treeModelHandler = treeModelHandler;
    }
    
    private DefaultTableModel createModelFromTable(Table t) {
        Number[][] data = new Number[t.getRowCount()][t.getColumnCount()];
        
        for(int i=0; i<t.getColumnCount(); i++) {
            for(int j=0; j<t.getRowCount(); j++) {
                data[j][i] = t.getColumn(i).getCell(j);
            }
        }
        
        DefaultTableModel m = new DefaultTableModel(data, t.getNames()) {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return table.getTypes()[columnIndex];
            }
        };

        return m;
    }
    
    private Table createTable() {
        Table t = null;
        String tableName = tableNameField.getText();
        
        int selectedEx = exerciseSelector.getSelectedIndex();
        switch (selectedEx) {
            case 0:
                t = new Table1(tableName);
                break;
        }

        if (t == null) {
            return null;
        }
        
        updateTable(t);
        
        return t;
    }
    
    private void updateTable(Table t) {
        t.clear();
        
        int rowCount = model.getRowCount();
        int colCount = model.getColumnCount();

        for(int j=0; j<colCount; j++) {
            t.getColumn(j);
            
            for (int i = 0; i < rowCount; i++) {
                Number val = (Number) model.getValueAt(i, j);
                t.getColumn(j).addCell(val);
            }
        }
    }
}
