package com.ourwork.tntnetworkslab.ui;

import com.ourwork.tntnetworkslab.core.items.Table1;
import com.ourwork.tntnetworkslab.core.items.Table;
import com.ourwork.tntnetworkslab.core.items.Table2;
import com.ourwork.tntnetworkslab.graph.GraphMaker;
import javax.swing.DefaultListModel;

/**
 *
 * @author Vasilis Naskos
 */
public class TableManager extends javax.swing.JFrame {

    private DefaultListModel model;
    private final TreeModelHandler modelHandler;
    
    /**
     * Creates new form TableManager
     */
    public TableManager() {
        initComponents();
        
        model = new DefaultListModel();
        tablesList.setModel(model);
        
        modelHandler = new TreeModelHandler() {
            @Override
            public void addTable(Table tb) {
                model.addElement(tb);
            }
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablesList = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        newTableButton = new javax.swing.JButton();
        removeTableButton = new javax.swing.JButton();
        EditTableButton = new javax.swing.JButton();
        importTableButton = new javax.swing.JButton();
        ExportTableButton = new javax.swing.JButton();
        graphButton = new javax.swing.JButton();
        aboutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Δίκτυα Τηλεπικοινωνιών και Μετάδοσης");

        jScrollPane2.setViewportView(tablesList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
        );

        newTableButton.setText("Δημιουργία");
        newTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTableButtonActionPerformed(evt);
            }
        });

        removeTableButton.setText("Διαγραφή");
        removeTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTableButtonActionPerformed(evt);
            }
        });

        EditTableButton.setText("Επεξεργασία");
        EditTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditTableButtonActionPerformed(evt);
            }
        });

        importTableButton.setText("Εισαγωγή");

        ExportTableButton.setText("Εξαγωγή");

        graphButton.setText("Γράφημα");
        graphButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphButtonActionPerformed(evt);
            }
        });

        aboutButton.setText("Πληροφορίες");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(newTableButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EditTableButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(importTableButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ExportTableButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(graphButton))
                    .addComponent(aboutButton))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {EditTableButton, ExportTableButton, aboutButton, graphButton, importTableButton, newTableButton, removeTableButton});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newTableButton)
                    .addComponent(removeTableButton)
                    .addComponent(EditTableButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(importTableButton)
                    .addComponent(ExportTableButton)
                    .addComponent(graphButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aboutButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTableButtonActionPerformed
        TableEditor editor = new TableEditor();
        editor.setLocationRelativeTo(null);
        editor.setVisible(true);
        editor.setTreeModelHandler(modelHandler);
    }//GEN-LAST:event_newTableButtonActionPerformed

    private void graphButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphButtonActionPerformed
        int selected = tablesList.getSelectedIndex();
        Table t = (Table) model.get(selected);
        Number[][] data = new Number[3][t.getRowCount()];
        
        if(t instanceof Table1) {
            Table1 t1 = (Table1) t;
            for(int j=0; j<t1.getRowCount(); j++) {
                data[0][j] = t1.getColumn(Table1.ColumnOrder.A).getCell(j);
                data[1][j] = t1.getColumn(Table1.ColumnOrder.B).getCell(j);
                data[2][j] = t1.getColumn(Table1.ColumnOrder.Q).getCell(j);
            }
        }
        else if (t instanceof Table2){
            Table2 t2 = (Table2) t;
            for(int j=0; j<t2.getRowCount(); j++) {
                data[0][j] = t2.getColumn(Table2.ColumnOrder.A).getCell(j);
                data[1][j] = t2.getColumn(Table2.ColumnOrder.B).getCell(j);
                data[2][j] = t2.getColumn(Table2.ColumnOrder.Q).getCell(j);
            }
            
        }
        else {
            return;
        }
        
        GraphMaker cm = new GraphMaker(t.getTableName(), data);
        cm.pack();
        cm.setLocationRelativeTo(null);
        cm.setVisible(true);
    }//GEN-LAST:event_graphButtonActionPerformed

    private void EditTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditTableButtonActionPerformed
        int selected = tablesList.getSelectedIndex();
        Table t = (Table) model.get(selected);
        
        TableEditor editor = new TableEditor(t);
        editor.setLocationRelativeTo(null);
        editor.setVisible(true);
        editor.setTreeModelHandler(modelHandler);
    }//GEN-LAST:event_EditTableButtonActionPerformed

    private void removeTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTableButtonActionPerformed
        int[] selected = tablesList.getSelectedIndices();
        for(int i=selected.length-1; i>=0; i--) {
            model.remove(selected[i]);
        }
    }//GEN-LAST:event_removeTableButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditTableButton;
    private javax.swing.JButton ExportTableButton;
    private javax.swing.JButton aboutButton;
    private javax.swing.JButton graphButton;
    private javax.swing.JButton importTableButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton newTableButton;
    private javax.swing.JButton removeTableButton;
    private javax.swing.JList tablesList;
    // End of variables declaration//GEN-END:variables

    
}
